apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: instana-operator-run-
spec:
  timeouts:
    pipeline: 6h0m0s
  pipelineRef:
    name: instana-operator
  params:
    - name: instana-password
      value: "fakepassword"
    # - name: user-valid-email
    #   value: "<your-valid-email>"
    - name: namespace
      value: "instana-operator"
    - name: storage-class
      value: "ocs-storagecluster-cephfs"
    - name: ocp-client-version
      value: "4.14"
    # - name: agent-key
    #   value: "<your-agent-key>"
    # - name: sales-key
    #   value: "<your-sales-key>"
    - name: docker-username
      value: "false"
    - name: docker-access-token
      value: "false"
  taskRunTemplate:
    podTemplate:
      securityContext:
        fsGroup: 65532
