apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: instana-operator-run-
spec:
  timeout: 6h0m0s
  pipelineRef:
    name: instana-operator
  params:
    # - name: instana-password
    #   value: "fakepassword"
    # - name: user-valid-email
    #   value: "valid-email"
    - name: namespace
      value: "instana-operator"
    - name: storage-class
      value: "ocs-storagecluster-cephfs"
    - name: ocp-client-version
      value: "4.12"
    # - name: agent-key
    #   value: "valid-agent-key"
    # - name: sales-key
    #   value: "valid-sales-key"
